apiVersion: v1
kind: Service
metadata:
  name: myapp-svc-headless
spec:
  type: NodePort
  selector:
    app: mysql-sts
  clusterIP: None
  ports:
  - name: mysql-svc
    port: 80
    targetPort: 8080
    nodePort: 30114